default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_starter_development
  username: postgres123
  password: postgres123
  host: localhost
test:
  <<: *default
  database: rails_starter_test
  username: postgres123
  password: postgres123
  host: localhost

production:
  <<: *default
  database: rails_starter_production
  username: rails_starter
  password: <%= ENV["RAILS_STARTER_DATABASE_PASSWORD"] %>
